Repository netlify/framework-info, pull requests merged in 2021-12, with the labels that each got.

#578 feat: process JSON files at build time
  .eslintrc.js
  .github/workflows/workflow.yml
  .gitignore
  package.json
  scripts/transform_json.js
  src/core.js
  src/frameworks/main.js
  test/frameworks.js
Labels: type: feature

#588 chore: allow pre-releases
  .github/workflows/pre-release.yml
  CONTRIBUTING.md
Labels: type: chore, automerge

#589 fix: remove `--ignore-scripts` from `npm publish` in prereleases
  .github/workflows/pre-release.yml
Labels: type: bug, automerge

#606 feat: updates for Next plugin 4
  .gitignore
  src/frameworks/next-nx.json
  src/frameworks/next.json
Labels: type: feature
