Repository netlify/framework-info, pull requests merged in 2021-06, with the labels that each got.

#283 fix(nuxt): update name
  src/frameworks/nuxt.json
Labels: type: bug

#300 feat: Add Cecil
  src/frameworks/cecil.json
  src/frameworks/main.js
Labels: type: feature

#308 feat: add SvelteKit
  src/frameworks/main.js
  src/frameworks/svelte-kit.json
  src/frameworks/svelte.json
Labels: type: feature

#315 feat: add WMR
  src/frameworks/main.js
  src/frameworks/wmr.json
Labels: type: feature

#323 chore(deps): ignore test-each updates for versions >=3
  renovate.json5
Labels: type: chore

#327 feat: add detection of Next with Nx
  src/frameworks/main.js
  src/frameworks/next-nx.json
  src/frameworks/next.json
Labels: type: feature
