Repository netlify/framework-info, pull requests merged in 2021-08, with the labels that each got.

#363 fix(dev): add list of excluded dev commands
  src/dev.js
  test/dev.js
  test/fixtures/excluded_script/package.json
Labels: type: bug

#299 feat: add auto installed plugin for gatsby
  src/frameworks/gatsby.json
Labels: status: blocked, type: feature

#366 chore: add kodiak
  .github/.kodiak.toml
Labels: type: chore

#378 feat(gatsby): precompile functions in develop
  src/frameworks/gatsby.json
Labels: type: feature

#380 fix(sveltekit): specify better output location
  src/frameworks/svelte-kit.json
Labels: type: bug

#397 chore(ci): cache npm cache dir between workflow execs
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
Labels: type: chore, automerge
