Repository netlify/framework-info, pull requests merged in 2021-05, with the labels that each got.

#243 feat: add Blitz.js support
  src/frameworks/blitz.json
  src/frameworks/main.js
Labels: type: feature

#253 chore: fix test coverage upload
  .github/workflows/workflow.yml
Labels: type: chore

#252 chore: run CI on latest Node.js
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
Labels: type: chore

#258 chore!: drop support for Node.js 8
  .github/workflows/workflow.yml
  package.json
  renovate.json5
Labels: type: chore

#259 feat: Add framework detection support for RedwoodJS
  src/frameworks/main.js
  src/frameworks/redwoodjs.json
Labels: type: feature

#274 chore(deps): configure renovate for Node.js 10 packages
  renovate.json5
Labels: type: chore

#281 fix(jekyll): add additional config files
  src/frameworks/jekyll.json
Labels: type: bug
