Repository netlify/framework-info, pull requests merged in 2021-02, with the labels that each got.

#118 chore: support Node 15
  .github/workflows/workflow.yml
Labels: type: chore

#124 feat: add nodeVersion option
  src/bin.js
  src/context.js
  src/main.js
  test/bin.js
  test/snapshots/bin.js.md
  test/snapshots/bin.js.snap
Labels: type: feature

#132 chore: fix linting and formatting on npm@7
  package.json
Labels: type: chore

#134 feat: add frameworks titles
  README.md
  src/core.js
  src/frameworks/angular.json
  src/frameworks/assemble.json
  src/frameworks/brunch.json
  src/frameworks/create-react-app.json
  src/frameworks/docpad.json
  src/frameworks/docusaurus-v2.json
  src/frameworks/docusaurus.json
  src/frameworks/eleventy.json
  src/frameworks/ember.json
  src/frameworks/expo.json
  src/frameworks/gatsby.json
  src/frameworks/gridsome.json
  src/frameworks/grunt.json
  src/frameworks/gulp.json
  src/frameworks/harp.json
  src/frameworks/hexo.json
  src/frameworks/hugo.json
  src/frameworks/jekyll.json
  src/frameworks/metalsmith.json
  src/frameworks/middleman.json
  src/frameworks/next.json
  src/frameworks/nuxt.json
  src/frameworks/parcel.json
  src/frameworks/phenomic.json
  src/frameworks/quasar-v0.17.json
  src/frameworks/quasar.json
  src/frameworks/react-static.json
  src/frameworks/roots.json
  src/frameworks/sapper.json
  src/frameworks/stencil.json
  src/frameworks/svelte.json
  src/frameworks/vue.json
  src/frameworks/vuepress.json
  src/frameworks/wintersmith.json
  test/frameworks.js
  test/snapshots/bin.js.md
  test/snapshots/bin.js.snap
  test/snapshots/main.js.md
  test/snapshots/main.js.snap
Labels: type: feature

#137 feat!: rename name property to id
  README.md
  site/react/App.jsx
  site/vanilla/index.html
  src/bin.js
  src/core.js
  src/frameworks/angular.json
  src/frameworks/assemble.json
  src/frameworks/brunch.json
  src/frameworks/create-react-app.json
  src/frameworks/docpad.json
  src/frameworks/docusaurus-v2.json
  src/frameworks/docusaurus.json
  src/frameworks/eleventy.json
  src/frameworks/ember.json
  src/frameworks/expo.json
  src/frameworks/gatsby.json
  src/frameworks/gridsome.json
  src/frameworks/grunt.json
  src/frameworks/gulp.json
  src/frameworks/harp.json
  src/frameworks/hexo.json
  src/frameworks/hugo.json
  src/frameworks/jekyll.json
  src/frameworks/metalsmith.json
  src/frameworks/middleman.json
  src/frameworks/next.json
  src/frameworks/nuxt.json
  src/frameworks/parcel.json
  src/frameworks/phenomic.json
  src/frameworks/quasar-v0.17.json
  src/frameworks/quasar.json
  src/frameworks/react-static.json
  src/frameworks/roots.json
  src/frameworks/sapper.json
  src/frameworks/stencil.json
  src/frameworks/svelte.json
  src/frameworks/vue.json
  src/frameworks/vuepress.json
  src/frameworks/wintersmith.json
  src/main.js
  test/bin.js
  test/detect.js
  test/frameworks.js
  test/helpers/main.js
  test/snapshots/bin.js.md
  test/snapshots/bin.js.snap
  test/snapshots/main.js.md
  test/snapshots/main.js.snap
Labels: type: feature

#139 feat!: rename title to name
  README.md
  src/core.js
  src/frameworks/angular.json
  src/frameworks/assemble.json
  src/frameworks/brunch.json
  src/frameworks/create-react-app.json
  src/frameworks/docpad.json
  src/frameworks/docusaurus-v2.json
  src/frameworks/docusaurus.json
  src/frameworks/eleventy.json
  src/frameworks/ember.json
  src/frameworks/expo.json
  src/frameworks/gatsby.json
  src/frameworks/gridsome.json
  src/frameworks/grunt.json
  src/frameworks/gulp.json
  src/frameworks/harp.json
  src/frameworks/hexo.json
  src/frameworks/hugo.json
  src/frameworks/jekyll.json
  src/frameworks/metalsmith.json
  src/frameworks/middleman.json
  src/frameworks/next.json
  src/frameworks/nuxt.json
  src/frameworks/parcel.json
  src/frameworks/phenomic.json
  src/frameworks/quasar-v0.17.json
  src/frameworks/quasar.json
  src/frameworks/react-static.json
  src/frameworks/roots.json
  src/frameworks/sapper.json
  src/frameworks/stencil.json
  src/frameworks/svelte.json
  src/frameworks/vue.json
  src/frameworks/vuepress.json
  src/frameworks/wintersmith.json
  test/frameworks.js
  test/snapshots/bin.js.md
  test/snapshots/bin.js.snap
  test/snapshots/main.js.md
  test/snapshots/main.js.snap
Labels: type: feature

#125 feat: add polling strategies
  README.md
  src/core.js
  src/frameworks/angular.json
  src/frameworks/brunch.json
  src/frameworks/create-react-app.json
  src/frameworks/docpad.json
  src/frameworks/docusaurus-v2.json
  src/frameworks/docusaurus.json
  src/frameworks/eleventy.json
  src/frameworks/ember.json
  src/frameworks/expo.json
  src/frameworks/gatsby.json
  src/frameworks/gridsome.json
  src/frameworks/harp.json
  src/frameworks/hexo.json
  src/frameworks/hugo.json
  src/frameworks/jekyll.json
  src/frameworks/middleman.json
  src/frameworks/next.json
  src/frameworks/nuxt.json
  src/frameworks/parcel.json
  src/frameworks/phenomic.json
  src/frameworks/quasar-v0.17.json
  src/frameworks/quasar.json
  src/frameworks/react-static.json
  src/frameworks/roots.json
  src/frameworks/sapper.json
  src/frameworks/stencil.json
  src/frameworks/svelte.json
  src/frameworks/vue.json
  src/frameworks/vuepress.json
  src/frameworks/wintersmith.json
  test/frameworks.js
  test/snapshots/bin.js.md
  test/snapshots/bin.js.snap
  test/snapshots/main.js.md
  test/snapshots/main.js.snap
Labels: type: feature

#146 fix: fix `files` in `package.json`
  package.json
Labels: type: bug

#150 Update the build command and directory for Angular.js
  src/frameworks/angular.json
Labels: type: chore
