Repository netlify/framework-info, pull requests merged in 2022-10, with the labels that each got.

#818 chore: updated SvelteKit framework info
  src/frameworks/svelte-kit.json
  src/frameworks/vite.json
Labels: type: chore, automerge

#819 feat: migrate from webpack to vite
  netlify.toml
  package-lock.json
  package.json
  scripts/webpack.config.core.js
  test/fixtures/config_files/package.json
  test/fixtures/empty/package.json
  test/fixtures/empty_dependencies/package.json
  vite.config.js
Labels: type: feature, automerge

#811 fix: use correct icon for Remix framework
  src/frameworks/remix.json
Labels: automerge

#792 fix: changed the Vite port to the new Vite default port 5173
  src/frameworks/vite.json
Labels: type: bug, automerge

#822 feat: detect installed version of framework
  .gitignore
  package-lock.json
  package.json
  src/context.js
  src/core.js
  src/main.js
  test/dev.js
  test/fixtures/monorepos/app1/package.json
  test/fixtures/monorepos/app2/package.json
  test/fixtures/monorepos/node_modules/next/package.json
  test/fixtures/multiple/node_modules/@vue/cli-service/package.json
  test/fixtures/multiple/node_modules/vuepress/package.json
  test/fixtures/simple/node_modules/sapper/package.json
  test/main.js
  test/snapshots/main.js.md
  test/snapshots/main.js.snap
  vite.config.js
Labels: type: feature, automerge

#825 feat: update next.js logos
  assets/logos/nextjs/dark-logo.svg
  assets/logos/nextjs/light-logo.svg
Labels: type: feature, automerge

#828 fix: update the files entry in package.json
  package.json
Labels: type: bug, automerge
