Repository netlify/framework-info, pull requests merged in 2022-08, with the labels that each got.

#803 refactor: remove site
  .babelrc
  .github/workflows/workflow.yml
  .gitignore
  cypress.json
  cypress/integration/e2e.js
  cypress/plugins/index.mjs
  cypress/run.js
  index.html
  package-lock.json
  package.json
  scripts/webpack.config.site.js
  site/react/App.jsx
  site/react/index.html
  site/react/index.jsx
Labels: type: chore, automerge

#805 fix: fixed typo in qwik excluded dependency
  src/frameworks/vite.json
Labels: type: bug

#797 feat: add Gatsby logo to returned framework info
  .gitignore
  assets/logos/gatsby/dark.svg
  assets/logos/gatsby/default.svg
  assets/logos/gatsby/light.svg
  index.html
  netlify.toml
  package-lock.json
  package.json
  scripts/transform_json.js
  src/core.js
  src/frameworks/gatsby.json
  test/frameworks.js
  test/snapshots/main.js.md
  test/snapshots/main.js.snap
Labels: type: feature, automerge

#808 feat: replace parcel logo name with parcel icon
  assets/logos/parcel/default.svg
Labels: type: feature, automerge

#812 feat: add a light-theme friendly logo for harp
  assets/logos/harp/light.svg
  src/frameworks/harp.json
Labels: type: feature, automerge

#813 feat: add detection for SolidJS
  assets/logos/solid-js/dark.svg
  assets/logos/solid-js/default.svg
  src/frameworks/main.js
  src/frameworks/solid-js.json
  src/frameworks/vite.json
Labels: type: feature, automerge
