Repository netlify/framework-info, pull requests merged in 2022-01, with the labels that each got.

#658 feat!: add Remix, make dev port optional
  src/frameworks/main.js
  src/frameworks/remix.json
  test/frameworks.js
Labels: type: feature

#663 fix(remix): use correct configuration file
  src/frameworks/remix.json
Labels: type: bug, automerge

#667 chore(deps): remove unneeded devDepedencies and switch to c8
  .gitignore
  package-lock.json
  package.json
Labels: type: chore, automerge

#669 chore: fix Husky
  .github/workflows/workflow.yml
  package-lock.json
  package.json
Labels: type: chore, automerge

#673 chore(docs-pr-template): add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: chore, automerge

#577 chore!: use pure ES modules
  .eslintrc.cjs
  README.md
  ava.config.js
  commitlint.config.cjs
  cypress.json
  cypress/integration/e2e.js
  cypress/plugins/index.js
  cypress/plugins/index.mjs
  cypress/run.js
  package.json
  scripts/transform_json.js
  scripts/webpack.config.core.js
  scripts/webpack.config.site.js
  site/react/App.jsx
  site/react/index.jsx
  src/context.js
  src/core.js
  src/detect.js
  src/dev.js
  src/frameworks/main.js
  src/main.js
  src/package.js
  src/plugins.js
  src/run_script.js
  test/detect.js
  test/dev.js
  test/frameworks.js
  test/helpers/main.js
  test/main.js
  test/options.js
  test/package.js
  test/run_script.js
Labels: type: chore, automerge

#677 chore: remove dead code
  cypress/integration/e2e.js
  package.json
  site/index.html
  site/vanilla/index.html
Labels: type: chore, automerge
